### PR TITLE
Multithreading

### PR DESCRIPTION
**Pull request by littleskunk**
https://github.com/Storj/dataserv-client/issues/136

### CODE REVIEW

**Comment by super3** [comment]
Have not tested this, but the unit tests seem to pass. Please add any relevant documentation to your pull.

**Comment by littleskunk** [comment]
Documentation done. Please check again.

**Comment by super3** [comment]
Seems like there is a conflict. Please resolve.

**Comment by littleskunk** [comment]
conflict solved and unit test passed again.

**Comment by super3** [comment]
At a glace it looks correct. @littleskunk What kind of performance increase did you get on testing. I'd like to have @F483 look this over before merging.

**Comment by littleskunk** [comment]
Testsetup with windows 7, intel core i5-4570, dataserv-client version 2.1.4, 
command "dataserv-client --max_size=10G --store_path=<HDD / RAM drive> build --set_height_interval=1000000
RAM drive 2:01 25% cpu
slow HDD 3:30 25% cpu

Now the same with this patch
command "dataserv-client --max_size=10G --store_path=<HDD / RAM drive> build --set_height_interval=1000000 --workers=4
RAM drive 00:36 100% cpu
slow HDD 3:24 ~25-30% cpu

command "dataserv-client --max_size=10G --store_path=<HDD / RAM drive> build --set_height_interval=1000000 --workers=2
RAM drive 01:00 50% cpu
slow HDD 3:02 ~30-35% cpu

**Pull request merged**
