### PR TITLE
Split client tests into unit tests and end-to-end tests

### PR DESCRIPTION
**Pull request by mtlynch**
The client tests are very slow to run and have external dependencies on a
running dataserv server.

This change splits up the client tests into end-to-end tests and unit tests,
where unit tests have no dependencies on external processes or global state.

The end-to-end tests exercise client-server interaction, but do not test
scenarios that are client or server focused. For example, there is no end to
end tests for double-registration of the same address because this is covered
by unit tests in both dataserv-client and dataserv (server). The end to end
tests are mainly positive tests of successful interaction between client and
server.

Also does some minor cleanup of the test code (removes multiple inheritance,
switches to context handler version of assertRaises).

### CODE REVIEW

**Comment by mtlynch** [comment]
I will fix the merge conflicts this evening

**Comment by mtlynch** [comment]
Fixed the merge conflicts, ready for review

**Comment by F483** [comment]
> coverage/coveralls — Coverage decreased (-20.3%) to 79.021% 

It seems you removed some vital tests, please ensure we do not loose coverage.

**Comment by mtlynch** [comment]
This pull request no longer works because api.py changed out from under it

**Pull request closed without merging**
