### PR TITLE
Builds shards in parallel

### PR DESCRIPTION
**Pull request by grmwld**
This pull request adds the options to specify a certain number of cores to build shards in parallel.
It leverages the python3 specific library concurrent.future, and thus needs picklable objects. Let me know if I should put the helper functions somewhere else.

I did not add tests, as I'm terrible at this. Let me know if they are a hard requirement and I'll give my best shot.

### CODE REVIEW

**Comment by F483** [comment]
I see several problems with this, but am not against merging it if they are resolved.

1. This breaks the resume functionality (will make many people unhappy), this will have to be fixed. One solution would be to add a max_cores value and have it resume from `shard_count -(max_cores+1)` currently it resumes form `shard_count - 1` in case the last shard is not complete.

2. It breaks tests, this needs to be fixed. We do not accept pull requests that break the unit tests. You should fix the code or the unit tests depending on which are wrong.

3. Does having a worker pool give any performance improvement and do you have benchmarks to back this up? I have not done this myself as I assumed drives have only one moving head and adding workers would not improve the situation because of this. I may be wrong though ... In any case I will not merge this and add extra complexity to the code base unless I have evidence to suggest that it is actually a worthwhile improvement.

4. Does it work on windows? I know windows has its own set of issues regarding multiprocessing and python.

If you do not have time to resolve these issues, I will do so myself. It is however not high on my priority list so it may take a while.

While I have some issues with this pull request, overall I think it is great and would like to thank you very much for contributing to the project!

**Comment by agrimaldi** [comment]
Thanks for the input and the quick reply ^^
I fully appreciate that this is far down on the priority list, however I just wanted to give it a shot. I will probably update this pull request quite slowly, since I do not have a lot of free time, but enjoy poking around at the code.

-1. I'll try to fix this

-2. I'm aware of the issues with the tests, I'm working on that at the moment. I have a seemingly working solution right now, but have some trouble with actually running the test suite:
If I just call:
```
python3 tests/test_builder.py
```

I end up with:
```
Seed: b'storj' with Audit Result: 2442550929857fd6046f7d4c53ef6a7360aee0f28c7b5ae3bdfdc02f7087c9ea in 0 seconds.
.Resuming from height 1
Saving seed 2c29455472dc3ea747053bce9fa1a2c08e79e1ae3a7efa3574d577698a2496ae with SHA-256 hash b6c98383b82e25c8d139406d1b79c9ff82998ade0735eb4108af78d98ec99e0c.
Saving seed e436d7ded37608517568b87ade825b1c20d920986c775f3e57677a71a0243620 with SHA-256 hash 7e36af06dff5d2200e7361a26c481d0faed89b8c8e7f7c3a697c29c4423acc8e.
..
----------------------------------------------------------------------
Ran 11 tests in 22.602s

OK
```

However, if I run:
```
coverage run --source="dataserv_client" setup.py test
```

I end up with:
```
test_on_generate_shard_callback (tests.test_builder.TestBuilder) ... INFO dataserv_client.builder 111: Resuming from height 1
INFO dataserv_client.builder 23: Saving seed 2c29455472dc3ea747053bce9fa1a2c08e79e1ae3a7efa3574d577698a2496ae with SHA-256 hash b6c98383b82e25c8d139406d1b79c9ff82998ade0735eb4108af78d98ec99e0c.
INFO dataserv_client.builder 23: Saving seed e436d7ded37608517568b87ade825b1c20d920986c775f3e57677a71a0243620 with SHA-256 hash 7e36af06dff5d2200e7361a26c481d0faed89b8c8e7f7c3a697c29c4423acc8e.
FAIL
test_sha256 (tests.test_builder.TestBuilder) ... ok
test_build (tests.test_client.TestClientBuild) ... INFO dataserv_client.messaging 51: Query: http://127.0.0.1:5000/api/address
WARNING dataserv_client.messaging 75: URLError(ConnectionRefusedError(61, 'Connection refused'),)
INFO dataserv_client.messaging 87: Query retry in 30 seconds.
```

- Is the FAIL related to what you were mentioning about the resume function ?
- Is there a way to get more sensible information about the reason test fail without having to manually hunt those ?
- Regarding the URLError, it seems the script tries to connect to localhost, so I guess the tests expect some kind of minimal driveshare server running ?
- Any general tips for how to properly run the test suite? (I'm quite unfamiliar with coverage.py)

-3. On a 2 core machine with an SSD:
```
$ time dataserv-client --url http://status.driveshare.org:5000 build --rebuild --num_cores 1
INFO dataserv_client.api 198: Starting build with 1 cores
INFO dataserv_client.api 45: Current height at 1.
INFO dataserv_client.api 45: Current height at 8.
INFO dataserv_client.api 213: Build finished

real	23.14s
user	18.93s
sys	1.47s


$ time dataserv-client --url http://status.driveshare.org:5000 build --rebuild --num_cores 2
INFO dataserv_client.api 198: Starting build with 2 cores
INFO dataserv_client.api 45: Current height at 1.
INFO dataserv_client.api 45: Current height at 8.
INFO dataserv_client.api 213: Build finished

real	13.69s
user	18.89s
sys	1.51s
```
I agree that in principle the operations are heavily io bound, and might benefit from some sort of non-blocking write coupled to a callback when saving the shard to the file with 
```python
RandomIO.RandomIO(seed).genfile(self.shard_size, path)
```

-4. I have no idea since I do not have a windows machine at my disposal.

**Comment by super3** [comment]
@agrimaldi Might be useful to implement this at a lower level on [RandomIO](https://github.com/storj/RandomIO), rather than the dataserv-client implementation. RandomIO is doing all the work for this anyway. Much less moving parts and tests to deal with. 

Plenty of people who would like to see this implemented(see #120), and would be willing to put down some SJCX to get it done.

**Comment by F483** [comment]
I agree with @super3 RandomIO is the better place to do this. Good to see an actual performance improvement by @agrimaldi. I think the potential improvement would also be greater in RandomIO.

**Comment by agrimaldi** [comment]
Alright guys, I'll give it a shot in RandomIO :)

Concerning my questions about running the test suite (point 2 of my previous post), do you have any advice? (better messages about failed tests, and the requests that are made on localhost during some parts of the tests)

Thanks for the feedback ^^

**Comment by super3** [comment]
Thanks. Will close for now. The errors you are getting are because you also need to run https://github.com/storj/dataserv on port 5000 for them to run properly. I've added #124 so this will be addressed in future documentation.

**Pull request closed without merging**
