### PR TITLE
Build shards in parallel

### PR DESCRIPTION
**Pull request by grmwld**
Leverages some changes made to RandomIO, so that the parallelization is done at a lower level. This is partially the result of the discussion following #112

See Storj/RandomIO#10

### CODE REVIEW

**Comment by agrimaldi** [comment]
I'm focusing on python3 right now, and travis fails the tests because my updated version of RandomIO is not taken into account (In particular because of the new class BatchRandomIO).

What is the proper way to fix this ?

**Comment by agrimaldi** [comment]
My pull request for multi-threaded RandomIO now passes tests. How do I make this PR pass tests since it requires Storj/RandomIO#10 ?

**Comment by F483** [comment]
I tested it locally on my machine and all tests passed (I installed your branch of RandomIO by building and install a wheel locally).

**Comment by F483** [comment]
We will be merging the solution from @littleskunk, while it is just a functional he supplied additional tests and documentation for it.

**Pull request closed without merging**
